apiVersion: v1
kind: Service
metadata:
  labels:
    app: schema-validator-api
  name: schema-validator-api
  namespace: integration
spec:
  ports:
  - name: "validator-api"
    port: 80
    targetPort: 8080
  selector:
    app: schema-validator-api