apiVersion: v1
kind: Service
metadata:
  name: cloud-wallet-backup-api-db
  namespace: integration
spec:
  ports:
  - port: 3306
    name: "cloud-api-db"
    targetPort: 3306
    protocol: TCP
  selector:
    name: cloud-wallet-backup-api-db
