apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cloud-wallet-backup-api-db
  namespace: integration
spec:
  selector:
    matchLabels:
      name: cloud-wallet-backup-api-db
  serviceName: "cloud-wallet-backup-api-db"
  template:
    metadata:
      labels:
        name: cloud-wallet-backup-api-db
    spec:
      containers:
        - name: cloud-wallet-backup-api-db
          image: mysql:5.7.32
          args:
            - "--ignore-db-dir=lost+found"
            - "--default-authentication-plugin=mysql_native_password"
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
            - "--innodb-buffer-pool-size=1G"
            - "--max-allowed-packet=1G"
            - "--wait-timeout=28800"
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 300
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
            failureThreshold: 5
          ports:
            - name: cloud-api-db
              containerPort: 3306
          envFrom:
            - secretRef:
                name: cloud-wallet-backup-api-db
          env:
            - name: MYSQL_DATABASE
              value: "cloud_wallet_backup_api"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: cloud-wallet-backup-api-db-data
  volumeClaimTemplates:
    - metadata:
        name: cloud-wallet-backup-api-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi
