apiVersion: v1
kind: Service
metadata:
  name: key-repository-api-db
  namespace: integration
spec:
  ports:
  - port: 3306
    name: "key-repo-db"
    targetPort: 3306
    protocol: TCP
  selector:
    name: key-repository-api-db
