apiVersion: v1
kind: Service
metadata:
  name: vc-schema-api-db
  namespace: integration
spec:
  ports:
  - port: 3306
    name: "vc-schema-db"
    targetPort: 3306
    protocol: TCP
  selector:
    name: vc-schema-api-db
