apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
  namespace: integration
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-portal
  template:
    metadata:
      labels:
        app: web-portal
    spec:
      containers:
      - image: ssi-registry.teda.th/ssi/web-portal/production:latest
        imagePullPolicy: Always
        name: web-portal
        ports:
          - name: frontend
            containerPort: 8080
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
      imagePullSecrets:
        - name: ssi-registry-secret

