apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mobile-api-cache
  name: mobile-api-cache
  namespace: integration
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mobile-api-cache
  template:
    metadata:
      labels:
        app: mobile-api-cache
    spec:
      containers:
      - image: redis:6.2.5-alpine
        imagePullPolicy: Always
        name: mobile-api-cache
        command:
          - redis-server
        ports:
        - containerPort: 6379
        resources: {}
