apiVersion: v1
kind: Service
metadata:
  labels:
    app: mobile-api-cache
  name: mobile-api-cache
  namespace: integration
spec:
  ports:
  - port: 6379
    name: "mobile-cache"
    targetPort: 6379
  selector:
    app: mobile-api-cache
