apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: did
  name: did
  namespace: core-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: did
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: did
    spec:
      containers:
      - image: ssi-registry.teda.th/ssi/ssi-core-api/production:latest
        imagePullPolicy: Always
        name: did
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
          - secretRef:
              name: blockchain-cache
          - secretRef:
              name: sentry-dsn
        env:
        - name: "TZ"
          value: "Asia/Bangkok"
        - name: APP_SERVICE
          value: DID
        - name: APP_HOST
          value: :8080
        - name: APP_ENV
          value: dev
        - name: APP_LOG_LEVEL
          value: debug
        - name: APP_DB_MONGO_HOST
          value: blockchain
        - name: APP_DB_MONGO_PORT
          value: '27017'
        - name: APP_DB_MONGO_NAME
          value: blockchain
        - name: APP_ABCI_ENDPOINT
          value: http://blockchain:26657
        - name: APP_DID_METHOD_DEFAULT
          value: idin
        - name: APP_DID_KEY_TYPE_DEFAULT
          value: EcdsaSecp256r1VerificationKey2019
      imagePullSecrets:
        - name: ssi-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
