apiVersion: v1
kind: Service
metadata:
  name: web-portal-api-db
  namespace: integration
spec:
  ports:
  - port: 3306
    name: "web-portal-db"
    targetPort: 3306
    protocol: TCP
  selector:
    name: web-portal-api-db
