apiVersion: v1
kind: Secret
metadata:
 name: ssi-registry-secret
 namespace: core-api
data:
    .dockerconfigjson: ${REGIS_BASE64}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
 name: ssi-registry-secret
 namespace: integration
data:
    .dockerconfigjson: ${REGIS_BASE64}
type: kubernetes.io/dockerconfigjson


