apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-repository-api
  namespace: integration
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: key-repository-api
  template:
    metadata:
      labels:
        app: key-repository-api
    spec:
      initContainers:
        - name: key-repository-api-migrate
          image: ssi-registry.teda.th/ssi/key-repository-api/production-migrate:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: key-repository-api-db
          env:
            - name: APP_DB_DRIVER
              value: mysql
            - name: APP_DB_HOST
              value: key-repository-api-db
            - name: APP_DB_PORT
              value: '3306'
            - name: APP_DB_NAME
              value: key_repository_api
      containers:
      - image: ssi-registry.teda.th/ssi/key-repository-api/production:latest
        imagePullPolicy: Always
        name: key-repository-api
        ports:
          - name: key-repo-api
            containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        envFrom:
          - secretRef:
              name: key-repository-api-db
          - secretRef:
              name: sentry-dsn
        env:
          - name: APP_HOST
            value: :8080
          - name: APP_ENV
            value: dev
          - name: APP_LOG_LEVEL
            value: debug
          - name: APP_DB_DRIVER
            value: mysql
          - name: APP_DB_HOST
            value: key-repository-api-db
          - name: APP_DB_PORT
            value: '3306'
          - name: APP_DB_NAME
            value: key_repository_api
        resources: {}
      imagePullSecrets:
        - name: ssi-registry-secret