apiVersion: v1
kind: Service
metadata:
  labels:
    app: key-repository-api
  name: key-repository-api
  namespace: integration
spec:
  ports:
  - name: "key-repo-api"
    port: 80
    targetPort: 8080
  selector:
    app: key-repository-api