apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloud-wallet-backup-api
  name: cloud-wallet-backup-api
  namespace: integration
spec:
  ports:
  - name: "cloud-api"
    port: 80
    targetPort: 8080
  selector:
    app: cloud-wallet-backup-api