apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vc-verify
  name: vc-verify
  namespace: core-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: vc-verify
  template:
    metadata:
      labels:
        app: vc-verify
    spec:
      containers:
      - image: ssi-registry.teda.th/ssi/ssi-core-api/staging:latest
        imagePullPolicy: Always
        name: vc-verify
        envFrom:
          - secretRef:
              name: blockchain-cache
          - secretRef:
              name: sentry-dsn
        env:
        - name: "TZ"
          value: "Asia/Bangkok"
        - name: APP_SERVICE
          value: VC_STATUS
        - name: APP_HOST
          value: :8080
        - name: APP_ENV
          value: dev
        - name: APP_LOG_LEVEL
          value: debug
        - name: APP_DB_MONGO_HOST
          value: blockchain
        - name: APP_DB_MONGO_PORT
          value: '27017'
        - name: APP_DB_MONGO_NAME
          value: blockchain
        - name: APP_ABCI_ENDPOINT
          value: http://blockchain:26657
        - name: APP_DID_METHOD_DEFAULT
          value: idin
        - name: APP_DID_KEY_TYPE_DEFAULT
          value: EcdsaSecp256r1VerificationKey2019
        - name: APP_JSON_SCHEMA_VALIDATOR_API_ENDPOINT
          value: http://schema-validator-api.integration.svc
        ports:
        - name: vc-verify
          containerPort: 8080
        resources: {}
      imagePullSecrets:
        - name: ssi-registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
