apiVersion: v1
kind: Service
metadata:
  labels:
    app: vc-verify
  name: vc-verify
  namespace: core-api
spec:
  ports:
    - name: "vc-verify"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vc-verify

