kind: Secret
apiVersion: v1
metadata:
  name: blockchain-cache
  namespace: core-api
  selfLink: /api/v1/namespaces/core-api/secrets/blockchain-cache
data:
  APP_DB_MONGO_PASSWORD: ${PASS_BASE64}
  APP_DB_MONGO_USERNAME: ${USER_BASE64}
  MONGO_INITDB_ROOT_PASSWORD: ${PASS_BASE64}
  MONGO_INITDB_ROOT_USERNAME: ${USER_BASE64}
type: Opaque
