apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: blockchain
  namespace: core-api
  name: blockchain
spec:
  selector:
    matchLabels:
      app: blockchain
  serviceName: "blockchain"
  replicas: 4
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      securityContext:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: blockchain-init-job
        image: tendermint/tendermint:v0.34.11
        volumeMounts:
            - mountPath: /tendermint
              name: tendermint
        env:
        - name: CONFIG_PATH
          value: /tendermint/config/config.toml
        command: ["/bin/sh","-c"]
        args: ["tendermint init; sed -i 's|127.0.0.1:26658|blockchain:26658|g' $CONFIG_PATH; sed -i 's|127.0.0.1:26657|0.0.0.0:26657|g' $CONFIG_PATH; sed -i 's|create_empty_blocks = true|create_empty_blocks = false|g' $CONFIG_PATH; sed -i 's|data/cs.wal/wal|.storage/tendermint/data/cs.wal/wal|g' $CONFIG_PATH"]
      containers:
      - name: blockchain
        image: ssi-registry.teda.th/ssi/ssi-core-api/production:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 26656
          - containerPort: 26657
        volumeMounts:
        - name: tendermint
          mountPath: /.storage/tendermint
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        envFrom:
          - secretRef:
              name: blockchain-cache
          - secretRef:
              name: sentry-dsn
        env:
        - name: "TZ"
          value: "Asia/Bangkok"
        - name: APP_SERVICE
          value: ABCI
        - name: APP_HOST
          value: :8080
        - name: APP_ENV
          value: dev
        - name: APP_LOG_LEVEL
          value: debug
        - name: APP_DB_MONGO_HOST
          value: 127.0.0.1
        - name: APP_DB_MONGO_PORT
          value: '27017'
        - name: APP_DB_MONGO_NAME
          value: blockchain
        - name: APP_ABCI_ENDPOINT
          value: http://blockchain:26657
        - name: APP_DID_METHOD_DEFAULT
          value: idin
        - name: APP_DID_KEY_TYPE_DEFAULT
          value: EcdsaSecp256r1VerificationKey2019
      - name: blockchain-cache
        image: mongo:4.4.2-bionic
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        ports:
          - containerPort: 27017
        envFrom:
          - secretRef:
              name: blockchain-cache
        volumeMounts:
          - mountPath: /data/db
            name: blockchain-cache
      imagePullSecrets:
        - name: ssi-registry-secret
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: tendermint
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: blockchain-cache
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 20Gi