apiVersion: v1
kind: Service
metadata:
  labels:
    app: blockchain
  name: blockchain
  namespace: core-api
spec:
  ports:
  - name: "rpc"
    port: 26656
    targetPort: 26656
    protocol: TCP
  - name: "p2p"
    port: 26657
    targetPort: 26657
    protocol: TCP
  - name: "mongo"
    port: 27017
    targetPort: 27017
  selector:
    app: blockchain
