apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal-api
  namespace: integration
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-portal-api
  template:
    metadata:
      labels:
        app: web-portal-api
    spec:
      initContainers:
        - name: web-portal-api-migrate
          image: ssi-registry.teda.th/ssi/web-portal-api/production-migrate:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: web-portal-api-db
          env:
            - name: APP_DB_DRIVER
              value: mysql
            - name: APP_DB_HOST
              value: web-portal-api-db
            - name: APP_DB_PORT
              value: '3306'
            - name: APP_DB_NAME
              value: web_portal
        - name: web-portal-api-seed
          image: ssi-registry.teda.th/ssi/web-portal-api/production-seed:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: web-portal-api-db
          env:
            - name: APP_DB_DRIVER
              value: mysql
            - name: APP_DB_HOST
              value: web-portal-api-db
            - name: APP_DB_PORT
              value: '3306'
            - name: APP_DB_NAME
              value: web_portal
            - name: APP_DID_SERVICE_BASE_URL
              value: http://did.core-api.svc
      containers:
      - image: ssi-registry.teda.th/ssi/web-portal-api/production:latest
        imagePullPolicy: Always
        name: web-portal-api
        ports:
          - name: web-portal-api
            containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        envFrom:
          - secretRef:
              name: web-portal-api-db
          - secretRef:
              name: sentry-dsn
        env:
          - name: APP_SERVICE
            value: WEB
          - name: APP_HOST
            value: :8080
          - name: APP_ENV
            value: dev
          - name: APP_LOG_LEVEL
            value: debug
          - name: APP_DB_DRIVER
            value: mysql
          - name: APP_DB_HOST
            value: web-portal-api-db
          - name: APP_DB_PORT
            value: '3306'
          - name: APP_DB_NAME
            value: web_portal
          - name: APP_DID_SERVICE_BASE_URL
            value: http://did.core-api.svc
          - name: APP_VC_SCHEMA_SERVICE_BASE_URL
            value: http://vc-schema
          - name: APP_VC_STATUS_SERVICE_BASE_URL
            value: http://vc-status.core-api.svc
          - name: APP_MOBILE_SERVICE_BASE_URL
            value: http://mobile-api
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
      imagePullSecrets:
        - name: ssi-registry-secret