apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-portal-api
  name: web-portal-api
  namespace: integration
spec:
  ports:
  - name: "web-portal-api"
    port: 80
    targetPort: 8080
  selector:
    app: web-portal-api