apiVersion: v1
kind: Service
metadata:
  labels:
    app: vc-status
  name: vc-status
  namespace: core-api
spec:
  ports:
    - name: "vc-status"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vc-status

