apiVersion: v1
kind: Service
metadata:
  name: mobile-api-db
  namespace: integration
spec:
  ports:
  - port: 3306
    name: "mobile-api-db"
    targetPort: 3306
    protocol: TCP
  selector:
    name: mobile-api-db