apiVersion: v1
kind: Service
metadata:
  name: mobile-api
  namespace: integration
spec:
  ports:
    - name: "mobile-api"
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: mobile-api