apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-portal
  name: web-portal
  namespace: integration
spec:
  ports:
  - name: "frontend"
    port: 80
    targetPort: 8080
  selector:
    app: web-portal

