apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-schema-api
  namespace: integration
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: vc-schema-api
  template:
    metadata:
      labels:
        app: vc-schema-api
    spec:
      initContainers:
        - name: vc-schema-api-migrate
          image: ssi-registry.teda.th/ssi/vc-schema-repository-api/staging-migrate:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: vc-schema-api-db
          env:
            - name: APP_DB_DRIVER
              value: mysql
            - name: APP_DB_HOST
              value: vc-schema-api-db
            - name: APP_DB_PORT
              value: '3306'
            - name: APP_DB_NAME
              value: vc_schema_api
        - name: vc-schema-api-seed
          image: ssi-registry.teda.th/ssi/vc-schema-repository-api/staging-seed:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: vc-schema-api-db
          env:
            - name: APP_DB_DRIVER
              value: mysql
            - name: APP_DB_HOST
              value: vc-schema-api-db
            - name: APP_DB_PORT
              value: '3306'
            - name: APP_DB_NAME
              value: vc_schema_api
      containers:
      - image: ssi-registry.teda.th/ssi/vc-schema-repository-api/staging:latest
        imagePullPolicy: Always
        name: vc-schema-api
        ports:
          - name: vc-schema-api
            containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
          failureThreshold: 5
        envFrom:
          - secretRef:
              name: vc-schema-api-db
          - secretRef:
              name: sentry-dsn
        env:
          - name: APP_HOST
            value: :8080
          - name: APP_ENV
            value: dev
          - name: APP_LOG_LEVEL
            value: debug
          - name: APP_DB_DRIVER
            value: mysql
          - name: APP_DB_HOST
            value: vc-schema-api-db
          - name: APP_DB_PORT
            value: '3306'
          - name: APP_DB_NAME
            value: vc_schema_api
          - name: APP_VC_SCHEMA_REPOSITORY_BASE_URL
            value: https://ssi-test.teda.th/api/schemas
          - name: APP_TOKEN_PREFIX
            value: FINEMA
          - name: APP_VALIDATOR_API_ENDPOINT
            value: http://schema-validator-api
        resources: {}
      imagePullSecrets:
        - name: ssi-registry-secret
