apiVersion: v1
kind: Service
metadata:
  labels:
    app: vc-schema-api
  name: vc-schema-api
  namespace: integration
spec:
  ports:
  - name: "vc-schema-api"
    port: 80
    targetPort: 8080
  selector:
    app: vc-schema-api